sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ridamcloud14/prod-react-app -f Dockerfile .

script:
  - docker run -e CI=true ridamcloud14/prod-react-app npm run test
